### ISSUE TITLE
Popup is only reacting on closePopupOnClick when it is not opened

### ISSUE THREAD

**Issue by atd-schubert** [yagajs/leaflet-ng2#116]
The function works, but not when it is already opened...

**Comment by 4thel00z** [comment]
Please add more intel, I would like to take care of this.

**Comment by atd-schubert** [comment]
At the moment the closePopupOnClick property works correct, if there is no popup open. When a popup is already open, the opened popup works like it was defined at the moment when it was opened.

In my opinion it is not a bad bug, but it would be straighter to handle like this. At the moment this issue is just something like a reminder...

**Comment by atd-schubert** [comment]
It works now...
