### ISSUE TITLE
Enhance dependency check

### ISSUE THREAD

**Issue by atd-schubert** [yagajs/leaflet-ng2#118]
At the moment we only use node-dependency, but I think it is a better behavior to check with `npm outdated` and return an error code, if the module has outdated dependencies. If there is no outdated library, it should run the `node-dependencies` additional, but it should catch the error-code, so it is just for your information.

Additionally we can ~~put this task to the travis ci~~ (use greenkeeper.io).

**Comment by marcjansen** [comment]
What about https://greenkeeper.io/ ?

We use it in several OSS projects and it is really good.

**Comment by atd-schubert** [comment]
Oh yes! This is better then the travis task, but I think for the package.json it is still a good idea...
