### ISSUE TITLE
Improve readme

### ISSUE THREAD

**Issue by atd-schubert** [yagajs/leaflet-ng2#129]
Use the readme from the release, maybe improve it a little bit and merge it into develop

**Comment by OpenSteveMap** [comment]
I'll work on the readme tomorrow ...

**Comment by atd-schubert** [comment]
You can also use the readme from the release branch

**Comment by OpenSteveMap** [comment]
I know ;)

**Comment by OpenSteveMap** [comment]
@atd-schubert I have done some imporvements on the readme. Please have a look on them in the readme branch. It is just a proposal at the moment.

**Comment by atd-schubert** [comment]
The way with angular-cli is just one way. The easiest to create a project, but to import yaga into your angular project, maybe an existing one, you just have to run `npm install --save @yaga/leaflet-ng2` and after that import the YagaModule into your TypeScript file.

I think we can also write how to use this module from the early beginning, or with angular-cli, but should rather explain the typical way of an easy install and import...

**Comment by atd-schubert** [comment]
Done in #264
