### ISSUE TITLE
Example for Attribution Control

### ISSUE THREAD

**Issue by OpenSteveMap** [yagajs/leaflet-ng2#136]
#### Attribution Control options:

- `[(prefix)]`
- `[(attribution)]`

#### Control options:

- `[position]`

**Comment by OpenSteveMap** [comment]
todo: add `[(attributions)]` to example

**Comment by OpenSteveMap** [comment]
After issue #137 (change prefix), we should change the prefix in this example, too.

**Comment by OpenSteveMap** [comment]
We still haven't done `[(attributions)]`

**Comment by atd-schubert** [comment]
We have to create an UI-Element `array-of-strings` in the example context first... Maybe I'll do this later...
