### ISSUE TITLE
Change prefix

### ISSUE THREAD

**Issue by OpenSteveMap** [yagajs/leaflet-ng2#137]
The map prefix is at the moment set to [yaga](https://yagajs.org).

We should change the prefix to [YAGA leaflet-ng2](https://leaflet-ng2.yagajs.org) (project server) or to [YAGA leaflet-ng2](https://github.com/yagajs/leaflet-ng2) (GitHub)

**Comment by OpenSteveMap** [comment]
The prefix has to be changed in:
- [attribution-control.directive.ts](https://github.com/yagajs/leaflet-ng2/blob/develop/ts/attribution-control.directive.ts#L34), line 34
- [attribution-control.directive.spec.ts](https://github.com/yagajs/leaflet-ng2/blob/develop/ts/attribution-control.directive.spec.ts#L54), line 54 and line 56

**Comment by atd-schubert** [comment]
Merged...
