### ISSUE TITLE
Enhance tile-layer example

### ISSUE THREAD

**Issue by OpenSteveMap** [yagajs/leaflet-ng2#140]
### Tile-Layer:

* `[(url)]: string` 
* `[maxNativeZoom]: number`
* `[minNativeZoom]: number`
* `[subdomains]: string[]` 
* `[errorTileUrl]: string`
* `[zoomOffset]: number`
* `[tms]: boolean`
* `[zoomReverse]: boolean`
* `[detectRetina]: boolean`
* `[crossOrigin]: boolean`

### Extends Layer

* `[tileSize] Number: Point`
* `[updateWhenIdle]: boolean`
* `[updateWhenZooming]: boolean`
* `[updateInterval]: number`
* `[bounds]: LatLngBounds`
* `[noWrap]: boolean`
* `[className]: string`
* `[keepBuffer]: number`

Event
* `(loading): Event`
* `(tileunload): TileEvent`
* `(tileloadstart): TileEvent`
* `(tileerror): TileErrorEvent`
* `(tileload): TileEvent`
* `(load): Event`

### Extends Layer Base

* `[(display)]: boolean`
* `[(opacity)]: number`
* `[(zIndex)]: number`
* `[minZoom]: number` in some cases 2-way-binded?
* `[maxZoom]: number` in some cases 2-way-binded?
* `[interactive]: boolean`
* `[attribution]: string`
* `[pane]: string` 

Layer Events
* `(add): Event`
* `(remove): Event`

Popup events (shown in this example?)
* `(popupopen): PopupEvent`
* `(popupclose): PopupEvent`

Tooltip events (shown in this example?)
* `(tooltipopen): TooltipEvent`
* `(tooltipclose): TooltipEvent`

Mouse Events
* `(click): MouseEvent`
* `(dbclick): MouseEvent`
* `(mousedown): MouseEvent`
* `(mouseover): MouseEvent`
* `(mouseout): MouseEvent`
* `(contextmenu): MouseEvent`

**Comment by atd-schubert** [comment]
We should wait for #167

**Comment by atd-schubert** [comment]
see PR #168
