### ISSUE TITLE
Give all layers min- and max-zoom

### ISSUE THREAD

**Issue by atd-schubert** [yagajs/leaflet-ng2#15]

**Comment by OpenSteveMap** [comment]
I think every Layer should have the option of minZoom and maxZoom. (All layers and not only a special kind of layer.) But it should also be an option not to set a value for minZoom and maxZoom.

**Comment by atd-schubert** [comment]
min and Max-Zoom are always optional parameters. The question is how to handle min and max-Zoom especially when there is no "native support" in leaflet, like on Image-Overlays. Then we have to take care to add or remove the overlay on a specific zoom-level...

**Comment by atd-schubert** [comment]
And in addition on layers with the possibility to change the min and max zoom levels the field should be 2 way binded, but on the overs it is just an input!

**Comment by atd-schubert** [comment]
We only implement the core leaflet functionality here. Maybe we can make a PR on Leaflet
