### ISSUE TITLE
Change Tile_Layer_URL to OSM_Tile_Layer_URL

### ISSUE THREAD

**Issue by OpenSteveMap** [yagajs/leaflet-ng2#170]
In Image-Overlay tests we should also use the url we have defined now in const.ts

Link to [Image-Overlay](https://github.com/yagajs/leaflet-ng2/blob/ebd8fad/ts/image-overlay.directive.spec.ts#L8)

@atd-schubert

**Comment by atd-schubert** [comment]
No, we use a special address for image overlay, not the osm tile one...
