### ISSUE TITLE
ERR! integrates with angular-CLI

### ISSUE THREAD

**Issue by Jerry-goodboy** [yagajs/leaflet-ng2#204]
##development environment

1. Mac
![image](https://cloud.githubusercontent.com/assets/9030784/24703660/b653851e-1a36-11e7-948b-fbacc92d3ee9.png)

2. vscode
![image](https://cloud.githubusercontent.com/assets/9030784/24703675/c7989396-1a36-11e7-8686-b5211485b4a4.png)

3. angular-cli to create angularV2 app, not angularV4 app
![image](https://cloud.githubusercontent.com/assets/9030784/24703718/f2a6fed8-1a36-11e7-9b91-44f56a206c05.png)

4. develop language:  typescript

5. error info
![image](https://cloud.githubusercontent.com/assets/9030784/24703627/8e2f6e4a-1a36-11e7-946c-f66afe34e9f5.png)

@marcjansen @atd-schubert @mks85 @mwheregroup @OpenSteveMap

**Comment by Jerry-goodboy** [comment]
@marcjansen @atd-schubert @OpenSteveMap @mks85 @mwheregroup

**Comment by atd-schubert** [comment]
I think you have a problem with different angular-core versions. We already replaced the dependency of angular with a peer dependency (look at [this](https://github.com/yagajs/leaflet-ng2/commit/3864881e6f3ff7f19715f52b980a5bc426786949#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R93)), but did not publish it in a release candidate. You should be able to test this issue quickly by removing the `node_modules/@angular` folder within the `@yaga/leaflet-ng2` folder. In your case you have to run a command like this:

```bash
rm -Rf /Users/lcd/app/angular2App/ygzx-ng2-leaflet-sass/node_modules/@yaga/leaflet-ng2/node_modules/@angular
```

*Alternatively you can install yaga/leaflet-ng2 from the github-repository and test it with the newest, but unpublished version*

After that you can try running `ng serve` again, like you describe before.

If this fixes your problem, please give a short feedback and we will publish a new release candidate to prevent the bug...

**Comment by kattsushi** [comment]
1+

**Comment by kaynz** [comment]
@atd-schubert 

Please publish a new release candidate. Removing the node_modules works as a workaround.

**Comment by atd-schubert** [comment]
Changes implemented into [RC5](https://github.com/yagajs/leaflet-ng2/releases/tag/1.0.0-rc5) and uploaded to [npm](https://www.npmjs.com/package/@yaga/leaflet-ng2)

**Comment by khalla** [comment]
I still got this error with ng build, i install the new version RC5, and still got the error:

![image](https://cloud.githubusercontent.com/assets/143278/25304611/c6b5cf8c-2762-11e7-8a24-84b1cb976b21.png)

Here is my package.json

{
  "name": "live",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^4.0.3",
    "@angular/common": "^4.0.3",
    "@angular/compiler": "^4.0.3",
    "@angular/core": "^4.0.3",
    "@angular/forms": "^4.0.3",
    "@angular/http": "^4.0.3",
    "@angular/material": "2.0.0-beta.3",
    "@angular/platform-browser": "^4.0.3",
    "@angular/platform-browser-dynamic": "^4.0.3",
    "@angular/router": "^4.0.3",
    "@types/leaflet": "1.0.60",
    "@yaga/leaflet-ng2": "^1.0.0-rc5",
    "bootstrap": "3.3.7",
    "breeze-bridge-angular2": "0.3.6",
    "breeze-client": "^1.5.3",
    "breeze-client-labs": "1.5.12",
    "core-js": "^2.4.1",
    "font-awesome": "^4.7.0",
    "hammerjs": "^2.0.8",
    "jquery": "3.1.0",
    "leaflet": "^1.0.3",
    "leaflet.vectorgrid": "^1.2.0",
    "moment": "2.18.1",
    "ngx-perfect-scrollbar": "4.0.0",
    "ngx-toastr": "5.0.6",
    "ngx-tooltip": "0.0.9",
    "primeng": "^4.0.0-rc.2",
    "primeui": "4.1.15",
    "rxjs": "^5.1.0",
    "zone.js": "^0.8.8"
  },
  "devDependencies": {
    "@angular/cli": "1.0.0",
    "@angular/compiler-cli": "^4.0.0",
    "@types/jasmine": "2.5.38",
    "@types/node": "~6.0.60",
    "codelyzer": "~2.0.0",
    "jasmine-core": "~2.5.2",
    "jasmine-spec-reporter": "~3.2.0",
    "karma": "~1.4.1",
    "karma-chrome-launcher": "~2.0.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^0.2.0",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.0",
    "ts-node": "~2.0.0",
    "tslint": "~4.5.0",
    "typescript": "~2.2.0"
  }
}

Thanks in advance...
