### ISSUE TITLE
Map container not found

### ISSUE THREAD

**Issue by kattsushi** [yagajs/leaflet-ng2#212]
```
...
import { YagaModule } from '@yaga/leaflet-ng2';
@NgModule({
  imports: [
    CommonModule,
    RouterModule,
    FormsModule,
    ReactiveFormsModule,
    FormlyModule,
    FormlyBootstrapModule,
    YagaModule, 
    NgbModule
  ],.
....
```

```
...
import { OSM_TILE_LAYER_URL } from '@yaga/leaflet-ng2';

@Component({
  selector: 'app-map',
  template: `
  <!--<div class="leaflet-maps" id="leaflet-maps"></div>--> 
       <yaga-map>
       <yaga-tile-layer [(url)]="tileLayerUrl"></yaga-tile-layer>
       </yaga-map>
  `,
  styleUrls: ['./map.component.scss']
})
export class MapComponent implements OnInit {
  public tileLayerUrl: string = OSM_TILE_LAYER_URL;
...
```

![image](https://cloud.githubusercontent.com/assets/12107518/25146098/ba088e34-2440-11e7-9fd4-b68fc079ef70.png)

can you help me with that?, thanks a lot and cheers! great work at this!

**Comment by atd-schubert** [comment]
I've made a test project, but cannot reproduce your error. You can have a look at this repo and check if you still have the error...

https://github.com/atd-schubert/leaflet-ng2-test-project

**Comment by kattsushi** [comment]
Thank you a lot is works now
i think that i miss this in my css files
```
.yaga-map {
  min-height: 800px;
}
```
Having a lot of fun here ..... I'm working and it's awesome to build code on this component

Cheers
