### ISSUE TITLE
Typo's in documentation leading to errors

### ISSUE THREAD

**Issue by khalla** [yagajs/leaflet-ng2#215]
Hi,  nice module, i will try it now.

I had some problems due to typo's in documentation.

You have:
This module works like a normal angular 2 module. You should do something like that:

import { YagaModule, OSM_TILE_LAYER_URL }   from '@**yaga/leflet-ng2'**;

Please change leflet to leaflet, lost a lot of time with this.

Thank you

**Comment by OpenSteveMap** [comment]
Sorry that you've lost a lot of time with it! The spelling of leaflet is now correct in the readme.md.
