### ISSUE TITLE
Does it work with Angular 4 CLI?

### ISSUE THREAD

**Issue by mickeyjohn** [yagajs/leaflet-ng2#217]
Hi,

I am trying with an Angular 4 app but still could not get the map display. What I did are:
- Create a new CLI app
- Import YagaModule in AppModule
- Import leaflet.js and .css in .angular-cli.json file.
- Finally, in app.component.html I added yaga map 

```
<yaga-map>
    <yaga-tile-layer [url]="'http://a.tile.openstreetmap.org/{z}/{x}/{y}.png'"></yaga-tile-layer>
</yaga-map> 
```

The map does not display then I got error message "Failed to load resource: net::ERR_INVALID_RESPONSE" in Chrome's console.

Any pointer is appreciated. Thanks.

**Comment by atd-schubert** [comment]
Maybe you have not give the map-component any size. You have to set this in css:
```css
.yaga-map {
  min-height: 200px;
} 
```

*BTW: You do not have to import leaflet.js in your `angular-cli.json`*

**Comment by atd-schubert** [comment]
Maybe the solution in issue #216 should help you, too...

**Comment by mickeyjohn** [comment]
Thanks for your help. Following #216, I get the map displayed but when zooming it floats around. Do you know why?
