### ISSUE TITLE
Multiple instances

### ISSUE THREAD

**Issue by mickeyjohn** [yagajs/leaflet-ng2#218]
Hi,
In the case of using mini maps or sync maps, there is a need to use multiple instances of map. Have yaga-leaflet-ng2 supported multiple instance yet?

Really appreciate your great work. Thanks a lot.

**Comment by atd-schubert** [comment]
Yes, that should be no problem to spawn multiple maps. We create a new DIV element for each component instance (look at [map-component line 281](https://github.com/yagajs/leaflet-ng2/blob/develop/ts/map.component.ts#L281))
