### ISSUE TITLE
Enhance IconDirective with retina, className and tooltip anchor options

### ISSUE THREAD

**Issue by OpenSteveMap** [yagajs/leaflet-ng2#220]

**Comment by OpenSteveMap** [comment]
- tooltip anchor

**Comment by atd-schubert** [comment]
`TooltipAnchor` is not part of the typing for `IconOptions`. I think we should first enhance the DefinitelyTyped definitions and add the tooltipAnchor property after that to our library

**Comment by atd-schubert** [comment]
TooltipAnchor is added to the official typings (https://github.com/DefinitelyTyped/DefinitelyTyped/pull/20889)
