### ISSUE TITLE
Leaflet Locate Control (new feat)

### ISSUE THREAD

**Issue by kattsushi** [yagajs/leaflet-ng2#221]
Hi pretty good work on this lib! i'm glad in make a PR to port this feature (plugin for leaflet).

https://github.com/domoritz/leaflet-locatecontrol

if you can show me the way to contribute if exist some guide for this.

Cheers!.

**Comment by atd-schubert** [comment]
In this library we only want to implement the functionality of the core leaflet. We can create another module to support this library, but we started developing an own extension, where you can customize the UI-Elements in the typical Angular2 way. If you want we can talk about this in a private conversation and publish the results in this issue.
