### ISSUE TITLE
Problem with ES6

### ISSUE THREAD

**Issue by lunanigra** [yagajs/leaflet-ng2#224]
Hello,

When using uglify-js (or in our case brunch uglify) we run on an error after including leaflet-ng2. Reason seems to be that uglify-js does not support ES6.

Is there a reason why you set target=es6 in tsconfig.json? When setting target=es5 uglify-js works.

Can you please set the target of your module to ES5?

Thanks, JC

**Comment by atd-schubert** [comment]
See also #213...

**Comment by atd-schubert** [comment]
There is also an error with android. In addition with cordova es6 code produces syntax errors.

We should switch to es5 back again in standard version...

**Comment by atd-schubert** [comment]
FYI: @kaynz

**Comment by lunanigra** [comment]
Any update? Cannot you simple change the tsconfig.json back to "es6" as quick fix. Or will this cause problems in other environments?

**Comment by atd-schubert** [comment]
I had no time the last days, but I am looking forward to make some enhancements this weekend

**Comment by atd-schubert** [comment]
See PR #227

**Comment by lunanigra** [comment]
@atd-schubert, thanks for the change! When will you create a new release making the update installable?
See... https://github.com/yagajs/leaflet-ng2/releases

**Comment by kaynz** [comment]
@lunanigra As you can see in #227 he's on it ;)

**Comment by lunanigra** [comment]
Thanks :relieved:

**Comment by atd-schubert** [comment]
@lunanigra @kaynz @-all the [new RC 6](https://leaflet-ng2.yagajs.org/1.0.0-rc6/) is out now...
