### ISSUE TITLE
Problems with some attributes in the icon directive

### ISSUE THREAD

**Issue by rolandaust** [yagajs/leaflet-ng2#225]
First of all thank you for the great module! I use the following code with what I have two problems. It would be great if you give me an advise what I'm doing wrong: 

`<yaga-map [lat]="mapGetLat()" [lng]="mapGetLng()" [zoom]="mapGetZoom()">
  <yaga-marker *ngFor="let station of stations" [lat]="station.coords.latidude" [lng]="station.coords.longitude">
    <yaga-icon [iconUrl]="mapIconUrl" [iconSize]="station.isActive ? [34, 34] : [20, 20]" [iconAnchor]="station.isActive ? [17, 32] : [10, 20]" [popupAnchor]="[0, -35]"></yaga-icon>
    <yaga-popup [minWidth]="400">
      Lorem ipsum
     </yaga-popup>
  </yaga-marker>
</yaga-map>`

1. They dynamic iconSize works, but produces javascript errors like `this._setIconStyles is not a function`

2.  The minWidth-Attribute on the popup-directive does not work and produces javascript errors like `Cannot read property 'style' of undefined`

Kind Regards
Roland

**Comment by atd-schubert** [comment]
After a quick research I think:

1. The source of the error is maybe located in the marker-directive in `ngAfterViewInit`. In addition most of the code in that method has to be placed in `ngAfterContentInit`. 
2. It seems to be a problem with the private leaflet function `(<any> this)._updateLayout();`. Maybe something like a polyfill with can help here.

I will take a look at it as soon as possible...

**Comment by lunanigra** [comment]
Any update? We would really appreciate getting this working... Please let me know if there is a way supporting you?

Thanks, JC

**Comment by atd-schubert** [comment]
It seems that the ContentChild DivIconDirective fulfills also to MarkerDirectives, because Markers are extended from the Div Markers. We will now prefer Icons before DivIcons.

**Comment by atd-schubert** [comment]
See PR #232
