### ISSUE TITLE
Marker Icons error

### ISSUE THREAD

**Issue by mits87** [yagajs/leaflet-ng2#226]
Hi, 

I use your library with angular 4.2 and I have problem with marker icons. 
When I embed map with marker:

```
<yaga-map lat="50.99992885585966" lng="6.999664306640626" zoom="10">
  <yaga-tile-layer [(url)]="tileLayerUrl"></yaga-tile-layer>
  <yaga-marker lat="50.99992885585966" lng="6.999664306640626" (click)="onMarkedClicked($event);"></yaga-marker>
</yaga-map>
```

I got this: https://www.dropbox.com/s/s1me91uik2sg6oy/Screenshot%202017-06-06%2013.37.12.png?dl=0

I have also second problem with click marker event. The method `onMarkedClicked` never dispatched! 
What's wrong with it?

Could you fix it?

**Comment by atd-schubert** [comment]
We fixed this issue already in #222, but did not make a new RC and published it on npm. After the other fixes I will make a new RC and publish it on npm...
