### ISSUE TITLE
Support crs parameter

### ISSUE THREAD

**Issue by fazpu** [yagajs/leaflet-ng2#265]
The use case is following: I would like to use the map for operations on floor plans. Hence, I do not want to operate with latitude / longitude, but rather with with simple x y coordinates.

Hence, I need to use the L.CRS.Simple option when initializing the map. An example could be found here: https://codepen.io/zachdunn/pen/VvRXdP.

Do you have any suggestions which components to change, how to approach this?

**Comment by atd-schubert** [comment]
Thanks for your PR including the example!

There are some minor changes I am going to make on the code:

* Provide the CRS interface / class in our module (#268)
* Open the external link in the example in a new window (#269)
* Add the CRS property to the map example (#270)
* Write unit-tests for the CRS property (#271)

**Comment by atd-schubert** [comment]
See in addition: #273
