### ISSUE TITLE
Provide guidance how to integrate leaflet plugins

### ISSUE THREAD

**Issue by fazpu** [yagajs/leaflet-ng2#266]
Please, would it be possible to add a documentation section about how to integrate leaflet plugins, such as leaflet.draw?
Thank you!

**Comment by fazpu** [comment]
I just found the https://github.com/yagajs/leaflet-ng2/issues/251. Sorry about that.

**Comment by atd-schubert** [comment]
I think we should write a short paragraph about this in the README.md to prevent further questions...

**Comment by atd-schubert** [comment]
See #273
