### ISSUE TITLE
Map not displaying properly

### ISSUE THREAD

**Issue by AshishTiwariMEAN** [yagajs/leaflet-ng2#286]
Hi, 
I have implement leaflet-n32 plugin in our structure, please have a look below code : 

app.componnents.ts:
```typescript
import { YagaModule, OSM_TILE_LAYER_URL }   from '@yaga/leaflet-ng2';
import { Component, NgModule, PlatformRef } from '@angular/core';
import { BrowserModule }                    from '@angular/platform-browser';
import { platformBrowserDynamic }           from '@angular/platform-browser-dynamic';


@Component({
    selector: 'app-root',
    templateUrl: './app.component.html',
})
export class AppComponent {
    // Your logic here, like:
    public tileLayerUrl: string = OSM_TILE_LAYER_URL;
}
```

app.module.ts : 
```typescript
import { YagaModule, OSM_TILE_LAYER_URL }   from '@yaga/leaflet-ng2';
import { Component, NgModule, PlatformRef } from '@angular/core';
import { BrowserModule }                    from '@angular/platform-browser';
import { platformBrowserDynamic }           from '@angular/platform-browser-dynamic';

const platform: PlatformRef = platformBrowserDynamic();
 import { AppComponent } from './app.component';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,YagaModule
    // AgmCoreModule.forRoot({
    //   apiKey: 'xxx'
    // })
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }

document.addEventListener('DOMContentLoaded', () => {
    platform.bootstrapModule(AppModule);
});
```

index.html :
```html 
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Angular4</title>
  <base href="/">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/x-icon" href="favicon.ico">
  
</head>
<body>
  <app-root></app-root>
</body>
</html>
```
Also please have a look attached output screen 
![picture_leaf](https://user-images.githubusercontent.com/18064298/32425025-3a219686-c2d6-11e7-8045-72484861d09c.png)

Can you please help me......

**Comment by AshishTiwariMEAN** [comment]
![leaflet_livebuid](https://user-images.githubusercontent.com/18064298/32428919-3a544898-c2ee-11e7-8c25-b9e4eda21dc4.png)

I have another problem, Once we create production build and try to run it then it's throwing error in browser console. can you please check and let me know better solution for the same.

**Comment by zverbeta** [comment]
You need set `tileLayerUrl` in your component and add this to yaga-tile-layer 

Something like this:
`<yaga-tile-layer [url]="tileLayerUrl"></yaga-tile-layer>`

**Comment by chuduyunhuan** [comment]
Hi,

I met this problem too. 
And, it is not about '<yaga-tile-layer [url]="tileLayerUrl"></yaga-tile-layer>', because I added it rightly. 
I think it may be related to css style, because when I debugged it in browser, the map size seems to be 0.

**Comment by AshishTiwariMEAN** [comment]
Yes, Also how we can pass lat and long in leaflet selector. is there any way then please suggest.

Need to display location according to the latitude and longitude. Can you please give any example for the same.

**Comment by zverbeta** [comment]
Okay, probably problem might in map height. Try set it `:host /deep/ .yaga-map { min-height:, 500px  }`

**Comment by zverbeta** [comment]
try to use this snippet

```html
<yaga-map
  [zoom]="17"
  [lat]="50.431782"
  [lng]="30.516382"
  [minZoom]="4"
  [maxZoom]="16">
  <yaga-zoom-control></yaga-zoom-control>
  <yaga-scale-control [metric]="true" [imperial]="false"></yaga-scale-control>
  <yaga-marker (click)="markerClick('click', $event);" [lat]="50.431782" [lng]="30.516382">
    <yaga-icon
      [iconUrl]="'./assets/marker-icon.png'"
      [iconSize]="[25, 41]"
      [iconAnchor]="[13, 41]"
      [shadowUrl]="'./assets/marker-shadow.png'"></yaga-icon>
      <yaga-popup>This is the content of the popup</yaga-popup>
  </yaga-marker>
  <yaga-tile-layer [url]="'http://a.tile.openstreetmap.org/{z}/{x}/{y}.png'"></yaga-tile-layer>
</yaga-map>
```

**Comment by atd-schubert** [comment]
I don't understand your problem, at the moment. According to your screenshot, I think you forgot to add the `leaflet.css`...

**Comment by atd-schubert** [comment]
@AshishTiwariMEAN Do you still have problem? Can you give us some feedback, or close this issue, please?
