### ISSUE TITLE
How to implement marker cluster

### ISSUE THREAD

**Issue by zverbeta** [yagajs/leaflet-ng2#288]
How to implement this if i using ```yaga-marker``` directive?

P/S Thanks for the work you've done!

**Comment by atd-schubert** [comment]
This is not easy to solve I think. I think there is something like a layer Provider missing, that makes it able to add marker to something different then the map.

I will think about this problem the next days, or on our hacking event in December...

**Comment by atd-schubert** [comment]
@zverbeta We do a lot of work to implement Providers (#290, #295) and make it much easier to convert Leaflet Plugins to YAGA ones. Can you take a look at the new Readme merged in #302 and give a feedback or close this issue?

Thanks and a happy new year 🎆
