### ISSUE TITLE
How to set new lat and lang if new values are on visible area? [question]

### ISSUE THREAD

**Issue by atiris** [yagajs/leaflet-ng2#292]
Hi, I use yaga-map component this way in html: (angular 5)
``` html
<yaga-map [(lat)]="lat" [(lng)]="lng" [(zoom)]="zoom" [minZoom]="5" [maxZoom]="18" (moveend)="mapMoveEnd($event)">
  <yaga-tile-layer [url]="tileLayerUrl"></yaga-tile-layer>
</yaga-map>
```
Initial coordinates set in component.ts file is loaded correctly.
Every change to place where new coordinates are not visible is correct, but when new coordinates are on the visible area of map, then map start moving, change back coordinates to temporary values and stop moving before go to target value.
So if visible area for lat is from 0 to 15 (actual point is 7) and you wan to move to point 14. You can go to 8, or to 9, or maybe to 14 but it is not always the same value. yaga map update lat back to 8 when starting move and stop.
You can test it with zoom 8 and move between Paris Rennes and Guernsey.

Part of constructor in my component.ts file:
``` typescript
    this.zoom = 8;
    // Roma
    setTimeout(() => { this.lat = 41.9102415; this.lng = 12.3959137; }, 5000);
    // Paris
    setTimeout(() => { this.lat = 48.8589507; this.lng = 2.2770201; }, 7000);
    // Rennes
    setTimeout(() => { this.lat = 48.1159675; this.lng = -1.7234739; }, 9000);
    // Guernsey
    setTimeout(() => { this.lat = 49.4469764; this.lng = -2.6034992; }, 11000);
```
Moving between Roma and Paris is OK. Paris is centered.
But move between Paris, Renness and Guermesey can end in any point between this places.

So how to set target lat and lng values and disable temporary changes from moving. I want to end with this values, not with values between actual value and my target value.

Thanks for help.

**Comment by atd-schubert** [comment]
I think this is more a problem with the event-emitting and syncing of the model and the view of angular. I would promise, that the positions are correct when you move your mouse randomly over the app (the app emits the mouse events and keep everything in sync).

Try to solve it with an [Observable](https://github.com/ReactiveX/rxjs) or an [EventEmitter](https://angular.io/api/core/EventEmitter)...

**Comment by atd-schubert** [comment]
Closed because this issue seems to be staled...
