### ISSUE TITLE
2-way-binded geojson for vector layers

### ISSUE THREAD

**Issue by atd-schubert** [yagajs/leaflet-ng2#30]
Maybe it is a good idea to add a 2-way-databinded property called geojson for all vector-layers.

Problems are for now on the Circle Layers, because GeoJSON does not support circles, just Points, but then we will lose the radius!

The other question is the data-type. Should we prefer GeoJSONGeometries or GeoJSONFeatures?

**Comment by atd-schubert** [comment]
Leaflet itself seems to give the GeoJSONFeature! I think this is the better choice...

**Comment by atd-schubert** [comment]
Maybe we can save the radius in the feature properties

**Comment by OpenSteveMap** [comment]
I think as feature we can save everything we want. Other softewares are working with the geoJSON geometry, but there they only save coordinates and nothing more. So no radius and no elevation ...

**Comment by OpenSteveMap** [comment]
We should have a closer look on that ... I think geojson could handle some stuff for us a bit easier, but i'm not sure if it should be the best prefered for all vector data.

**Comment by atd-schubert** [comment]
Implemented as mentioned
