### ISSUE TITLE
Problems while updating zoom level and new center for the map.

### ISSUE THREAD

**Issue by Prashanth-Thomas** [yagajs/leaflet-ng2#319]
This is more of a question. How would one have to make the map move to a newly assigned center(lat. lng) with a new zoom level???

lets say i have 3 textboxes and a button. One textbox accepts latitude value and the other a longitude value. The 3rd text box accepts the zoom level(any number between 6 to 16).

when i click on the button the map below it should recenter itself to the latitude and longitude specified and also apply the zoom factor specified.

How would i make the map do this?

I have tried the following:
<yaga-map
        [zoom]="zoomVal"
        [lat]="centralLatitude"
        [lng]="centralLongitude">
.
.
.
.
</yaga-map>

Internally in my TS file of this component i assign the textbox values to the respective variables.
The result is: the zoom does not apply. the longitude(x-axis) shift the point to the center the latitude does not apply.

Any help would be great, Thanks :)

**Comment by atd-schubert** [comment]
Normally Angular keeps all the data in the model in sync. So you just have to change the value in your input, like this:

```html
<yaga-map [zoom]="zoomVal" [lat]="latVal" [zoom]="lngVal"></yaga-map
Zoom: <input type="number" [(ngModel)]="zoomVal"/>
Lat: <input type="number" [(ngModel)]="latVal"/>
Lng: <input type="number" [(ngModel)]="lngVal"/>
```

If you want to apply the changes only by submitting the button you have to create another property in your controller like this:

```html
<yaga-map [zoom]="currentZoomVal" [lat]="currentLatVal" [zoom]="currentLngVal"></yaga-map
Zoom: <input type="number" [(ngModel)]="newZoomVal"/>
Lat: <input type="number" [(ngModel)]="newLatVal"/>
Lng: <input type="number" [(ngModel)]="newLngVal"/>
<input type="button" (click)="applyZoomAndCenter()"/>
```

In your `applyZoomAndCenter`method you have to do something like this:

```typescript
class AppComponent {
  // ...
  public applyZoomAndCenter() {
    this.currentZoomVal = this.newZoomVal;
    this.currentLatVal = this.newLatVal;
    this.currentLngVal = this.newLngVal;
  }
}
```

Solves this your issue? Please close it, if it does...

**Comment by Prashanth-Thomas** [comment]
@atd-schubert I had used the exact same code with respect to the button implementation.
![initial](https://user-images.githubusercontent.com/30317537/35958102-f460db00-0cc4-11e8-9e72-a9ab625ff761.PNG)

The code is as follows

HTML
```html
<div style="height: 500px">
  Lat
  <input [(ngModel)]="newLatVal" type="text">
  Lng
  <input [(ngModel)]="newLngVal" type="text">
  ZoomVal
  <input [(ngModel)]="newZoomVal" type="text">

  <button (click)="changeMapCenterAndZoom()">Click</button>
  <yaga-map
    [zoom]="currentZoomVal"
    [lat]="currentLatVal"
    [lng]="currentLngVal"
    [minZoom]="1"
    [maxZoom]="20">
    <yaga-zoom-control></yaga-zoom-control>
    <yaga-scale-control [metric]="true" [imperial]="false"></yaga-scale-control>
    <yaga-marker [lat]="currentLatVal" [lng]="currentLngVal">
      <yaga-icon
        [iconUrl]="'./assets/marker-icon.png'"
        [iconSize]="[25, 41]"
        [iconAnchor]="[13, 41]"
        [shadowUrl]="'./assets/marker-shadow.png'"></yaga-icon>
      <yaga-popup>This is the content of the popup</yaga-popup>
    </yaga-marker>
    <yaga-tile-layer [url]="tileLayerUrl">
    </yaga-tile-layer>
  </yaga-map>
</div>
```

Component Code
```typescript
export class WorldMapComponent {
  tileLayerUrl: string;
  newLatVal= 53;
  newLngVal = 8;
  newZoomVal = 10;
  centerLatVal= 53;
  centerLngVal = 8;
  centerZoomVal = 10;
  switchData: any;
  constructor() {
     /*OSM_TILE_LAYER_URL this is imported*/
     this.tileLayerUrl = OSM_TILE_LAYER_URL;
 }


  changeMapCenterAndZoom() {
    this.centerLatVal = this.newLatVal;
    this.centerLngVal = this.newLngVal;
    this.centerZoomVal = this.newZoomVal;
  }
}
```

In the above code, the marker gets the new latitude and longitude value and plots them properly each time. 
But the map does not center to the new Latitude and new Longitude, the Zoom also messes up at times.

Ran few manual tests and tried to deduce when the map centers wrongly.
Found out that wen all the 3 values change, the map centering acts funny.

Here are few examples for when they fail:
Example 1 Values:
**Latitude Longitude   Zoom    Status**
___53_______8________10___Initial(Pass)
___53.88___8.66______16_______Pass
___54_______8_________15_______Fail

Example 2 Values:
**Latitude Longitude   Zoom    Status**
___53_______8________10___Initial(Pass)
___54______8.6_______15_______Pass
___53_______8________16_______Fail

When i say status = Fail, it means that the marker has plotted fine. But the re-centering to that point with the right zooming failed. It re-centers in another location(noticed that the longitude is right, but the latitude and zoom isn't right).

**Comment by atd-schubert** [comment]
I recognized a similar problem in a specific browser. Before I take a closer look at this issue, can you take a look into your Web-Inspector and tell me your error message, if you have one? I just guess that you have a problem after changing your value to a "blank" value. After that in some browsers a string is returned as value. You can fix it by rewriting the method like this:

```typescript
changeMapCenterAndZoom() {
    this.centerLatVal = parseFloat(this.newLatVal);
    this.centerLngVal = parseFloat(this.newLngVal);
    this.centerZoomVal = parseFloat(this.newZoomVal);
}
```

Does it work for you now?

**Comment by Prashanth-Thomas** [comment]
Hi, tried this, made sure that every variable type involved here was a number. Also made the text box type a number. But did not seem to work.

So just to make sure. I tried the following.
Removed the three textbox related to latitude, longitude and zoom.
Only placed 2 buttons which help in shifting the position of the centered latitude, longitude and zoom level.

![capture](https://user-images.githubusercontent.com/30317537/36058312-cf02c722-0e42-11e8-996d-f608b924d201.PNG)

Used the following code

```
//Initial values
centerLatVal= 53;
centerLngVal = 8;
centerZoomVal = 10;
```

In html above the map code added the following
```
<button (click)="shift1Call()">Shift 1</button>
<button (click)="shift2Call()">Shift 2</button>
```

Placed 2 functions each function related to its respective button
```
  shift1Call(){
    this.centerLatVal = 53.88;
    this.centerLngVal = 8.66;
    this.centerZoomVal = 16;
  }

  shift2Call(){
    this.centerLatVal= 54;
    this.centerLngVal = 8;
    this.centerZoomVal = 15;
  }
```
Even after implementing these changes, faced the same issue. The center Lat and Lng values are linked to a marker and the maps [lat] and  [lng] properties (which deal with centralizing the map to the specified point). The marker seems to be shifting to the correct position. But the centralizing and zoom factor of the map doesn't seem to move to the desired position. The zoom also fails to apply at times. This happens when all three values are changed. Again, it works for the 1st time perfectly, ie: when button "Shift 1" is clicked, the shift, centralizing and zooming happens as intended. It fails when button "Shift 2" is clicked.

Tested this in Firfox and Chrome. Both resulted in the same issue.

**Comment by swan-front-end** [comment]
You can use "setView" method. It's solved problem for me.

**Comment by Prashanth-Thomas** [comment]
@vlad-mokryi Brilliant, this works perfectly.

In case anyone reads this in future and has a similar issue, follow the below steps
1. Place an Id on the yaga-map element
`<yaga-map #yagaMapId>`

2. Use 'ViewChild' in the component to get a hold of the map in your code.
`@ViewChild('yagaMapId') yagaMapId;`

3. Use the following code where change in Lat, Lng or Zoom occurs
`this.yagaMapId.setView([this.centerLatVal, this.centerLngVal], this.centerZoomVal);`
