### ISSUE TITLE
Make new release with the fix for the "ImageOverlay has no provider" issue

### ISSUE THREAD

**Issue by fazpu** [yagajs/leaflet-ng2#322]
Unfortunatelly it seems like the fix for https://github.com/yagajs/leaflet-ng2/issues/306 has not been included in the lates release.

Please, make a new one if possible with the fix.

Thank you!

**Comment by atd-schubert** [comment]
#306 was merged with #307, take a look at: https://github.com/yagajs/leaflet-ng2/blob/3633637/ts/image-overlay.directive.ts#L25

**Comment by atd-schubert** [comment]
There is a new RC, now. Maybe this fixes your problem @fazpu
