### ISSUE TITLE
1.0.0-rc10 uses leaflet-1.2.0, although 1.0.0-rc9 uses leaflet-1.3.1

### ISSUE THREAD

**Issue by AnatolyStrakhov** [yagajs/leaflet-ng2#384]
Hi All,

I upgraded yaga-leaflet from 1.0.0-rc9  to 1.0.0-rc10 and have regressions. I suppose the root cause is that 1.0.0-rc10 downgrades the leaflet.

In fresh project  I did
`npm install @yaga/leaflet-ng2@1.0.0-rc9`
It installed leaflet **1.3.1**.

In fresh project  I did
`npm install @yaga/leaflet-ng2@1.0.0-rc10`
It installed leaflet **1.2.0**.

Could you take a look at that please?

**Comment by AnatolyStrakhov** [comment]
package.json of 1.0.0-rc9
```  "dependencies": {
    "@types/geojson": "^7946.0.0",
    "@types/leaflet": "^1.2.5",
    "leaflet": "^1.2.0"
  }
```

package.json of 1.0.0-rc10
```  "dependencies": {
    "@types/geojson": "^7946.0.0",
    "@types/leaflet": "^1.2.5",
    "leaflet": "1.2.0"
  }
```

**Comment by atd-schubert** [comment]
Yes that is true, there is a bug with the WMS Layer in 1.3.1. This is why we fixed the version. For further information take a look at #364.

We wait for the next release of Leaflet, that includes the already in the repository fixed issue.

**Comment by atd-schubert** [comment]
@AnatolyStrakhov take a look at PR #403
