### ISSUE TITLE
marker's double click event doesn't work

### ISSUE THREAD

**Issue by lixujia** [yagajs/leaflet-ng2#389]
I was using (dbclick)="onMarkerDbClicked(marker)" to bind dbclick event(using leaflet-ng2 master branch), but the function wasn't called when double clicked.
And I found in marker.directive.ts the code:
`this.on('dbclick', (event: LeafletMouseEvent) => {
        this.dbclickEvent.emit(event);
  });`
After change dbclick to dblclick, marker double click call back can work.
Is this a typo of source code?

**Comment by atd-schubert** [comment]
You are right! I fixed it immediately...
