### ISSUE TITLE
DivIcon & IconSize

### ISSUE THREAD

**Issue by jochenjonc** [yagajs/leaflet-ng2#390]
With leaflet-ng2 I'm unable to set the iconSize of a yaga-div-icon so that the default white square isn't visible. It is possible to set the size to [0, 0], but this still draws a little dot on the map.

There was an [issue](https://github.com/Leaflet/Leaflet/issues/4238#issuecomment-291903827) on the leafletjs GitHub site about this and the solution there was too set the iconSize to null.

I've updated the fiddle the was part of the issue a little but to show how leaflet does it: http://jsfiddle.net/s1duc9mm/2/

When I do the same with leaflet-ng2, it seem that iconSize with value null is ignored and not passed to leafletjs.

**Comment by atd-schubert** [comment]
This is more an issue with the leaflet css styles then with our module, but it is a known issue.
We had already implemented something that helps you out with that: All leaflet div icon wrapper that are YAGA instances have the class attribute `yaga-div-icon`. With that CSS class you are able to change this behavior like you wish.

A quick example:

```css
.yaga-div-icon {
    background-color: transparent;
    border: 0;
}

**Comment by atd-schubert** [comment]
@jochenjonc does this fix your problem? Can you give additional feedback or close this issue?

**Comment by jochenjonc** [comment]
@atd-schubert it fixed the problem, but I had to use the following in my components scss file:

```
:host ::ng-deep .yaga-div-icon { 
    background-color: transparent;
    border: 0;
}
```
