### ISSUE TITLE
Is there any possiblity to add Google Satellite Layer?

### ISSUE THREAD

**Issue by ganigapeta** [yagajs/leaflet-ng2#394]
Is there any way that we can use google satellite layer view on yaga-leaflet? I see one plugin which works with leaflet, please see the below reference links.

https://gitlab.com/IvanSanchez/Leaflet.GridLayer.GoogleMutant

Demo: https://ivansanchez.gitlab.io/Leaflet.GridLayer.GoogleMutant/demo.html

**Comment by atd-schubert** [comment]
I don't know this plugin... There might be several possibilities to add this Plugin to your project. At least you can try it like described in [the README file](https://github.com/yagajs/leaflet-ng2#use-standard-leaflet-plugins).

**Comment by ganigapeta** [comment]
@atd-schubert  Sure I will try as described, and I see couple threads which you already answered. Thanks!
