### ISSUE TITLE
Not able to add CQL_FILTER in setparams for layers

### ISSUE THREAD

**Issue by dev-amitkmishra** [yagajs/leaflet-ng2#400]
I have different layers coming from geoserver and on one of the layer I need to implement filters, for that I am trying to set :
  this.mapComponent.addLayer(this.roof_geoServer.setParams(
      {
          layers: 'my_location_history',
          format: 'image/png',
          transparent: true,
          CQL_FILTER: "prediction=\'Flat\'"
      }
  ));
But, I am getting the error of 'there is no any property like CQL_FILTER'. Please helo in solving this issue or in a way I can apply filter on a layer.

**Comment by atd-schubert** [comment]
Do you try using `cql_filter` (in lower case) according to [this](https://gis.stackexchange.com/questions/248495/refreshing-wms-based-on-updated-cql-filter-in-leaflet#249854) Answer?

In addition you should not use `addLayer` to add a WMS layer. Prefer the YAGA WML-Layer directive instead...
