### ISSUE TITLE
TileLayer Subdomains: first tile is wrong

### ISSUE THREAD

**Issue by jochenjonc** [yagajs/leaflet-ng2#415]
Hi,

I'm using Yaga in combination with HERE map tiles, but the first tile that get's fetched is on an unknown subdomain, resulting in a gray square on the map.

This is my code:

`<yaga-tile-layer yaga-base-layer="HERE" [(url)]="hereLayerUrl" [subdomains]="hereSubdomains"></yaga-tile-layer>`

```
  public hereLayerUrl = `https://{s}.base.maps.cit.api.here.com/maptile/2.1/maptile/newest/normal.day/{z}/{x}/{y}/256/png8?app_id=${environment.here.app_id}&app_code=${environment.here.app_code}&lg=eng`;
  public hereSubdomains: string[] = ['1', '2', '3', '4'];
```

But the first tile that gets fetched has the following url: https://**c**.base.maps.cit.api.here.com/maptile/2.1/maptile/newest/normal.day/10/521/342/256/png8?app_id=xyz&app_code=xyz&lg=eng

It calls subdomain c instead of 1 to 4.

Is this a bug or is something misconfigured on my end?

Regards,

Jochen

**Comment by atd-schubert** [comment]
This seems to be easy to fix. I will give it a try later.
