### ISSUE TITLE
Rectangular selection to move multiple objects on the map at once;

### ISSUE THREAD

**Issue by DmitriyIvanko** [yagajs/leaflet-ng2#438]
**Is your feature request related to a problem? Please describe.**
The user often expects rectangular selection of objects, like on the desktop.

**Describe the solution you'd like**
Rectangular selection to move multiple objects on the map at once;

**Additional context**
Thank you for your tool! If it possible please let me know!

**Comment by atd-schubert** [comment]
This is maybe an extension, but leaflet-ng2 should only implement leaflet 1:1 to Angular.io. So it is not the right repo here...
