### ISSUE TITLE
Inject Tooltips and Popups into directives

### ISSUE THREAD

**Issue by atd-schubert** [yagajs/leaflet-ng2#46]
We should add `Tooltips` and `Popups` as `ContentChild`

**Comment by atd-schubert** [comment]
Most of the directives have now a binding to Tooltip and Popup, excluding the raster layers. The question is, if they need, or should have this implemented?

**Comment by OpenSteveMap** [comment]
I think it can be useful for raster layers, too... e.g. if you have a picture of an old map, a tooltip with name and date of the old map could be a interesting information.

**Comment by OpenSteveMap** [comment]
I think we should do that for raster layers, too ... Cause in some cases it is useful and in the cases where it is not useful nobody has to use it ...

**Comment by atd-schubert** [comment]
The Popup and Tooltip directive can be inserted optionally
