### ISSUE TITLE
Write an example for image-overlay

### ISSUE THREAD

**Issue by atd-schubert** [yagajs/leaflet-ng2#56]
We can write our own example with 2way-binded bootstrap-interfaces. Maybe with an own image-overlay or with the one from [this example](http://leafletjs.com/reference-1.0.2.html#imageoverlay).

**Comment by OpenSteveMap** [comment]
### from image-overlay:

`[(url)]: string`
`[crossOrigin]: boolean`
`[alt]: string`
`[(north)]: number`
`[(south)]: number`
`[(east)]: number`
`[(west)]: number`
`[(bounds)]: L.LatLngBounds`

### from Layer:

`[(display)]: boolean`
`[(opacity)]: number`
`[(zIndex)]: number`
`[minZoom]: number in some cases 2-way-binded`
`[maxZoom]: number in some cases 2-way-binded`
`[interactive]: boolean`
`[attribution]: string`
`[pane]: string`

`(click): MouseEvent`
`(dbclick): MouseEvent`
`(mousedown): MouseEvent`
`(mouseover): MouseEvent`
`(mouseout): MouseEvent`
`(contextmenu): MouseEvent`
`(add): Event`
`(remove): Event`
`(popupopen): PopupEvent`
`(popupclose): PopupEvent`
`(tooltipopen): TooltipEvent`
`(tooltipclose): TooltipEvent`

**Comment by OpenSteveMap** [comment]
@atd-schubert not supported are:
- `minZoom`
- `maxZoom`
- `zIndex`
- `attribution`
- `pane`

**Comment by OpenSteveMap** [comment]
@atd-schubert there is a bug in the image-overlay:

- The url is not working correctly
- The image is permanently shown on the map with an opacity value from the example
- Only the image over the permanent image can be handled by changing coordinate values
- By using display true/false you can add more images
- By zooming it was possible to add an 3rd image

**Comment by atd-schubert** [comment]
OK, I will take a look...

**Comment by atd-schubert** [comment]
Merged...
