### ISSUE TITLE
Register styles for leaflet with a function

### ISSUE THREAD

**Issue by atd-schubert** [yagajs/leaflet-ng2#89]
Maybe it would be a nice feature to register the css styles needed to display leaflet maps by a function. Something like `registerStyles();`

In addition it would also be nice to give the possibility to set different color-schemas, like `registerStyles({ defaultLineColor: '#f00' });`

**Comment by OpenSteveMap** [comment]
I think to register styles is a good idea ...

**Comment by atd-schubert** [comment]
I think about this issue again and the problem is that the css style from leaflet is licensed unter a different license. That means that we have to mention that explicit. I think we should do not include source code under a different license in this project. Maybe we can make an additional module just for that, or use [an existing one](https://www.npmjs.com/package/leaflet-css), but this module is not conform with TypeScript definitions.

Maybe the best is that everybody have to care for the styles himself!
